package app.geniusfiles.mobile

import android.content.Intent
import android.graphics.Color
import android.graphics.drawable.ColorDrawable
import android.os.Build
import android.os.Bundle
import android.content.res.Configuration
import android.content.res.Resources
import android.webkit.CookieManager
import androidx.appcompat.app.AppCompatDelegate
import androidx.core.view.WindowCompat
import androidx.core.view.WindowInsetsControllerCompat
import com.getcapacitor.BridgeActivity

/**
 * GeniusFiles Capacitor entry point.
 *
 * Overrides the default MainActivity generated by `cap add android`
 * so the native file-system plugins get registered before the WebView
 * bridge boots.
 *
 * Le mode choisi est relu avant `super.onCreate` afin que le splash, la
 * fenêtre et la WebView partagent la même apparence dès la première frame.
 */
class MainActivity : BridgeActivity() {
    companion object {
        const val THEME_PREFS = "GeniusFilesTheme"
        const val THEME_MODE = "mode"
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        // Register BEFORE super.onCreate so the Capacitor bridge finds
        // the plugin while wiring the WebView — otherwise JS gets
        // `window.Capacitor.Plugins.GeniusFilesNative === undefined`
        // and every file listing fails with "Plugin unavailable".
        registerPlugin(GeniusFilesNativePlugin::class.java)
        // Biométrie du coffre-fort (AndroidX Biometric). Sans cet
        // enregistrement, `window.Capacitor.Plugins.GeniusFilesBiometric`
        // est absent et l'app annonce « non disponible » à tort.
        registerPlugin(GeniusFilesBiometricPlugin::class.java)
        // « Ouvrir avec… » entrant : une autre application peut confier un
        // fichier à GeniusFiles (ACTION_VIEW / EDIT / SEND).
        registerPlugin(GeniusFilesIntentPlugin::class.java)
        // Surveillance de stabilité : journalisation technique assainie
        // envoyée à Crashlytics (aucune donnée personnelle, aucun chemin).
        registerPlugin(GeniusFilesCrashlyticsPlugin::class.java)
        // Mesure d'usage global (Google Analytics for Firebase) : vues
        // d'écran logiques et propriétés techniques uniquement — aucune
        // donnée personnelle, aucun nom ni chemin de fichier.
        registerPlugin(GeniusFilesAnalyticsPlugin::class.java)
        // Source de vérité unique côté Android : le mode nuit AppCompat est
        // aligné sur le choix persisté AVANT toute inflation. Le thème
        // DayNight, le splash (values-night), `windowLightStatusBar` et les
        // ressources partagent alors la même apparence dès la première frame
        // — c'est ce qui manquait quand « Clair » était choisi sur un
        // téléphone en thème sombre (fond sombre + barre d'état noire).
        applyNightMode()
        // Le thème système réel + le mode choisi sont publiés dans des
        // cookies AVANT le chargement de la page : le script de pré-peinture
        // les lit de façon synchrone, même si le localStorage de la WebView
        // a été purgé par le système.
        publishThemeCookies()
        // Le splash système utilise une couleur jour/nuit (choix Android).
        // Si l'utilisateur a forcé Clair ou Sombre, on impose la bonne
        // couleur de fenêtre AVANT l'inflation : plus aucune frame au
        // mauvais thème, ni flash noir, ni flash blanc.
        try {
            val light = isLightTheme()
            window.setBackgroundDrawable(
                ColorDrawable(if (light) 0xFFF5F6F8.toInt() else 0xFF191919.toInt()),
            )
            WindowInsetsControllerCompat(window, window.decorView).apply {
                isAppearanceLightStatusBars = light
                isAppearanceLightNavigationBars = light
            }
        } catch (_: Throwable) {
            /* fenêtre pas encore prête — applySystemBars() reprendra */
        }
        super.onCreate(savedInstanceState)

        // L'intent de lancement peut porter un fichier à ouvrir : il est
        // mémorisé ici et résolu à la demande par la WebView.
        GeniusFilesIntentPlugin.offer(this, intent)

        applySystemBars()
        disableAlgorithmicDarkening()
        disableWebViewOverScroll()
    }

    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        // `launchMode=singleTask` : quand l'app tourne déjà, le fichier
        // arrive ici et non dans onCreate.
        setIntent(intent)
        GeniusFilesIntentPlugin.offer(this, intent)
        // Un appui sur un widget alors que l'app tourne déjà : la WebView est
        // prévenue pour consommer la nouvelle route (aucun rechargement).
        notifyWebLaunchIntent()
    }

    /** Réveille le consommateur JS de l'intent de lancement. */
    private fun notifyWebLaunchIntent() {
        try {
            val webView = bridge?.webView ?: return
            webView.post {
                webView.evaluateJavascript(
                    "window.dispatchEvent(new CustomEvent('gf:launch-intent'))",
                    null,
                )
            }
        } catch (_: Throwable) {
            /* pont pas encore prêt — onCreate a déjà mémorisé l'intent */
        }
    }

    override fun onConfigurationChanged(newConfig: Configuration) {
        super.onConfigurationChanged(newConfig)
        // `uiMode` est géré sans recréer l'Activity : la WebView conserve sa
        // route, sa pile de navigation et tout l'état utilisateur.
        applySystemBars()
        publishThemeCookies()
        notifyWebSystemTheme()
    }

    override fun onResume() {
        super.onResume()
        applyNightMode()
        // Certaines ROM réinitialisent l'apparence des barres au retour au
        // premier plan : on la ré-impose systématiquement.
        applySystemBars()
        publishThemeCookies()
        notifyWebSystemTheme()
    }

    /**
     * Le thème système courant, INDÉPENDANT du choix utilisateur.
     *
     * `resources.configuration` refléterait le mode nuit forcé par
     * AppCompatDelegate ; `Resources.getSystem()` expose la configuration
     * réelle du téléphone, seule valeur exploitable pour le mode auto.
     */
    fun isSystemLight(): Boolean =
        (Resources.getSystem().configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK) !=
            Configuration.UI_MODE_NIGHT_YES

    /**
     * Aligne le mode nuit AppCompat sur le choix persisté. Sans recréation
     * d'activité (`configChanges` inclut `uiMode`) : aucun écran noir,
     * aucune perte d'état ni de navigation.
     */
    fun applyNightMode() {
        val target = when (savedThemeMode()) {
            "light" -> AppCompatDelegate.MODE_NIGHT_NO
            "dark" -> AppCompatDelegate.MODE_NIGHT_YES
            else -> AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM
        }
        if (AppCompatDelegate.getDefaultNightMode() != target) {
            AppCompatDelegate.setDefaultNightMode(target)
        }
    }

    /**
     * `gf_sys` = thème du téléphone, `gf_mode` = choix utilisateur persisté.
     * Écrits sur les deux origines possibles du serveur local Capacitor.
     */
    fun publishThemeCookies() {
        try {
            val cm = CookieManager.getInstance()
            cm.setAcceptCookie(true)
            val sys = if (isSystemLight()) "light" else "dark"
            val mode = savedThemeMode()
            for (origin in arrayOf("https://localhost", "http://localhost")) {
                cm.setCookie(origin, "gf_sys=$sys; path=/; max-age=31536000")
                cm.setCookie(origin, "gf_mode=$mode; path=/; max-age=31536000")
            }
            cm.flush()
        } catch (_: Throwable) {
            /* WebView indisponible — le fallback JS reste en place */
        }
    }

    /** Notifie la WebView sans recharger : aucun écran noir, aucun reflow. */
    private fun notifyWebSystemTheme() {
        val light = isSystemLight()
        try {
            val webView = bridge?.webView ?: return
            webView.post {
                webView.evaluateJavascript(
                    "window.dispatchEvent(new CustomEvent('gf:system-theme',{detail:{light:$light}}))",
                    null,
                )
            }
        } catch (_: Throwable) {
            /* pont pas encore prêt */
        }
    }

    /**
     * L'assombrissement algorithmique du WebView repeint la page en sombre
     * (« couche noire ») et provoque un écran noir lors d'un changement de
     * thème système. GeniusFiles gère lui-même ses deux thèmes.
     */
    private fun disableAlgorithmicDarkening() {
        try {
            val webView = bridge?.webView ?: return
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                @Suppress("DEPRECATION")
                webView.settings.forceDark = android.webkit.WebSettings.FORCE_DARK_OFF
            }
            webView.setBackgroundColor(if (isLightTheme()) 0xFFF5F6F8.toInt() else 0xFF191919.toInt())
        } catch (_: Throwable) {
            /* réglage non supporté */
        }
    }

    /**
     * Supprime l'étirement natif de la WebView au dépassement du scroll.
     *
     * Chromium étire (ou fait rebondir) l'intégralité de la surface rendue,
     * en-tête collant compris : aucun CSS ne peut l'en empêcher. Coupé ici,
     * seul l'effet de tirage géré par l'application reste visible, et il
     * ne s'applique qu'au contenu situé sous l'en-tête.
     */
    private fun disableWebViewOverScroll() {
        try {
            val webView = bridge?.webView ?: return
            webView.overScrollMode = android.view.View.OVER_SCROLL_NEVER
            webView.isVerticalScrollBarEnabled = false
            webView.isHorizontalScrollBarEnabled = false
        } catch (_: Throwable) {
            /* WebView indisponible */
        }
    }

    /**
     * Edge-to-edge natif : la WebView dessine sous les barres système,
     * qui restent parfaitement transparentes, sans scrim ni contraste forcé.
     * Le contraste des icônes est déduit du choix explicite ou du thème
     * Android quand le mode automatique est actif.
     */
    fun applySystemBars(lightOverride: Boolean? = null) {
        WindowCompat.setDecorFitsSystemWindows(window, false)

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            // Paysage : la fenêtre s'étend jusqu'aux bords courts, découpe
            // (display cutout) comprise — plus aucune bande noire latérale.
            window.attributes = window.attributes.apply {
                layoutInDisplayCutoutMode =
                    android.view.WindowManager.LayoutParams
                        .LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES
            }
        }

        @Suppress("DEPRECATION")
        run {
            window.statusBarColor = Color.TRANSPARENT
            window.navigationBarColor = Color.TRANSPARENT
        }


        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            // Supprime le voile que le système applique automatiquement
            // derrière les barres transparentes.
            window.isStatusBarContrastEnforced = false
            window.isNavigationBarContrastEnforced = false
        }

        val light = lightOverride ?: isLightTheme()
        // Filet de sécurité derrière la WebView et pendant ses frames de
        // composition : aucune fenêtre noire lors d'un changement de thème.
        window.setBackgroundDrawable(ColorDrawable(if (light) 0xFFF5F6F8.toInt() else 0xFF191919.toInt()))
        try {
            bridge?.webView?.setBackgroundColor(if (light) 0xFFF5F6F8.toInt() else 0xFF191919.toInt())
        } catch (_: Throwable) {
            /* WebView pas encore créée */
        }
        val controller = WindowInsetsControllerCompat(window, window.decorView)
        controller.isAppearanceLightStatusBars = light
        controller.isAppearanceLightNavigationBars = light
    }

    fun savedThemeMode(): String =
        getSharedPreferences(THEME_PREFS, MODE_PRIVATE).getString(THEME_MODE, "system") ?: "system"

    fun isLightTheme(): Boolean = when (savedThemeMode()) {
        "light" -> true
        "dark" -> false
        else -> isSystemLight()
    }
}
